name:                fridge
version:             0.1.0.0
github:              "githubuser/fridge"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fridge#readme>

dependencies:
- base >= 4.7 && < 5
- Spock
- aeson
- text
- mtl
- containers
- timers
- suspend

library:
  source-dirs: src
  ghc-options:
  - -freverse-errors
  - -Wall
  - -Werror
  - -Wincomplete-patterns

executables:
  fridge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fridge

tests:
  fridge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -freverse-errors
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wincomplete-patterns
    dependencies:
    - fridge
    - hspec
