name:                fridge-server
version:             0.1.0.0
github:              "githubuser/fridge-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fridge-server#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- data-default
- fridge-core
- http-types
- lucid
- shakespeare
- suspend
- text
- time
- timers
- unordered-containers
- vector
- yesod
- yesod-core
- yesod-form
- yesod-lucid
- yesod-static


library:
  source-dirs: src

executables:
  fridge-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fridge-server

tests:
  fridge-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fridge-server
    - yesod-test
    - hspec
